AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Mock Interview API using FastAPI and Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.9
    Environment:
      Variables:
        MONGODB_URI: !Sub '{{resolve:secretsmanager:${AWS::StackName}/mongodb:SecretString:uri}}'
        OPENAI_API_KEY: !Sub '{{resolve:secretsmanager:${AWS::StackName}/openai:SecretString:key}}'
        LOG_LEVEL: INFO

Resources:
  InterviewAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_function.zip
      Handler: lambda_handler.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /mock-interview-api
            Method: ANY
            Stage: default
        HealthCheckEvent:
          Type: Api
          Properties:
            Path: /health
            Method: GET
            Stage: default
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:interview-app/*'
      EphemeralStorage:
        Size: 512

  InterviewAPILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${InterviewAPI}'
      RetentionInDays: 30

Outputs:
  InterviewAPI:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/default/'
  InterviewAPIFunction:
    Description: Interview API Lambda Function ARN
    Value: !GetAtt InterviewAPI.Arn
  InterviewAPILogGroup:
    Description: CloudWatch Log Group for Interview API
    Value: !Ref InterviewAPILogGroup 